apiVersion: v1
kind: Secret
metadata:
  name: template-ui-secrets
  labels:
    app: template-ui
    component: ui
type: Opaque
stringData:
  COOKIE_SIGN: ""
  SSO_CLIENT_ID: ""
  SSO_CLIENT_SECRET: ""

